version: '3'
services:
  backend:
    container_name: backend
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - 27017:27017 

  mongo-express:
    restart: unless-stopped
    container_name: mongo_express
    image: mongo-express
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo